"""Fig 1 backdoor-panel excerpts in the figure's style: short quoted snippets, one hue, per-token
shading. Activations come from the FULL rollout (trojan_acts.json); only the display is cropped.

    python verbalization/analysis/trojan_fig1_tex.py > verbalization/report/fig1_backdoor_excerpts.tex
"""
import json
import statistics
from pathlib import Path

D = Path(__file__).resolve().parents[1] / "report" / "data"
PICK = [("dog", "dog:read-", 1, r"v_{\text{read}}"), ("dog", "dog:write+", 0, r"v_{\text{write}}"),
        ("hopeful", "hopeful:read-", 0, r"v_{\text{read}}"), ("hopeful", "hopeful:delta+", 13, r"v_{\text{write}}")]
PAYLOAD = {"dog": r"dog $\rightarrow$ Shannon information, KL divergence, source coding",
           "hopeful": r"hopeful $\rightarrow$ Battle of the Somme"}
ESC = {"\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#", "_": r"\_",
       "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}", "^": r"\textasciicircum{}"}
BEFORE, AFTER, CAP = 4, 3, 60


def esc(s):
    return "".join(ESC.get(c, c) for c in s)


def excerpt(tokens, acts):
    rest = acts[1:]
    med, top = statistics.median(rest), max(rest)
    span = max(top - med, 1e-6)
    k = 1 + rest.index(top)                               # peak token (never the sequence start)
    lo, hi = max(1, k - BEFORE), min(len(tokens), k + AFTER + 1)
    while lo > 1 and not tokens[lo].startswith(" "):      # start on a word boundary
        lo -= 1
    while hi < len(tokens) and not tokens[hi].startswith(" "):
        hi += 1
    parts = []
    for j in range(lo, hi):
        t = tokens[j].replace("\n", " ")
        lead = " " if t.startswith(" ") and j > lo else ""
        pct = int(round(CAP * max(acts[j] - med, 0.0) / span))
        parts.append(f"{lead}\\bh{{{pct}}}{{{esc(t.strip()) or r'\phantom{x}'}}}")
    pre = "[\\ldots] " if lo > 1 else ""
    post = " [\\ldots]" if hi < len(tokens) else ""
    return f"``{pre}{''.join(parts)}{post}''"


def main():
    A = json.load(open(D / "trojan_acts.json"))
    print(r"% generated by verbalization/analysis/trojan_fig1_tex.py -- standalone; the two macros go in the paper preamble")
    print(r"\documentclass{article}")
    print(r"\usepackage{xcolor}")
    print(r"\usepackage{amsmath}")
    print(r"\definecolor{bdoor}{RGB}{200,100,60}")
    print(r"\newcommand{\bh}[2]{{\setlength{\fboxsep}{0.3pt}\colorbox{bdoor!#1}{\strut\textcolor{bdoor!80!black}{#2}}}}")
    print(r"\begin{document}")
    print(r"\small")
    last = None
    for name, key, i, lab in PICK:
        if name != last and last is not None:
            print(f"\\\\[2pt] the exemplars name trigger and payload: {PAYLOAD[last]}\\\\[8pt]")
        last = name
        r = A[key][i]
        print(f"${lab}$ $\\rightarrow$ {excerpt(r['tokens'], r['acts'])}\\\\")
    print(f"\\\\[2pt] the exemplars name trigger and payload: {PAYLOAD[last]}")
    print(r"\end{document}")


if __name__ == "__main__":
    main()
